---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cities":
    get:
      summary: list cities
      responses:
        "200":
          description: successful
    post:
  summary: create city
  parameters:
    - name: name
      in: body
      required: true
      schema:
        type: object
        properties:
          name:
            type: string
            example: "New City Name"

  "/api/v1/cities/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show city
      responses:
        "200":
          description: successful
    patch:
      summary: update city
      responses:
        "200":
          description: successful
    put:
      summary: update city
      responses:
        "200":
          description: successful
    delete:
      summary: delete city
      responses:
        "200":
          description: successful
servers:
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
