default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_car_api_development
  min_messages: debug

test:
  <<: *default
  database: book_car_api_test

production:
  <<: *default
  host: <%= ENV["BOOK_CAR_API_DATABASE_HOST"] %>
  database: book_car_api_production
  username: <%= ENV["BOOK_CAR_API_DATABASE_USERNAME"] %>
  password: <%= ENV["BOOK_CAR_API_DATABASE_PASSWORD"] %>
